### ISSUE TITLE
Unable to retrieve image error during OKE cluster deployment

### ISSUE THREAD

**Issue by norbsch** [rancher-plugins/kontainer-engine-driver-oke#54]
When I try to install a new OKE cluster from Rancher I always get an “unable to retrieve image” error message. Cluster deployment is successful but node pool deployment does not start at all. I tried to use existing VCN and let the Rancher create the VCN but faced the same issue.when I try to install a new OKE cluster from Rancher I always get a “cannot find node image” error message. Cluster deployment is successful but node pool deployment does not start at all. I tried to use existing VCN and let the Rancher create the VCN but faced the same issue.
OKE cluster driver v1.8.1, OCI node driver v1.2.0, OKE v1.23.4, Rancher v2.6.7
<img width="817" alt="Screenshot 2022-08-28 at 19 45 25" src="https://user-images.githubusercontent.com/37214567/187262500-ccd5687e-5903-4ced-8e3a-ad3a80337733.png">

**Comment by jlamillan** [comment]
Thanks for the bug report.

This issue appears to be caused by a mismatch between the way [Rancher Server fetches available image IDs](https://github.com/rancher/rancher/blob/master/pkg/api/norman/customization/oci/listers.go#L212) (via `containerengine`) and the way the[ OKE cluster driver fetches images IDs](https://github.com/rancher-plugins/kontainer-engine-driver-oke/blob/master/oke/oke_manager_client.go#L397) (`compute`).

The compute API knows about `Oracle-Linux-7.9-2022.06.30-0` for example, but not `Oracle-Linux-7.9-2022.06.30-0-OKE-1.23.4-392`.

These pre-configured OKE specialty images are important, so we can update the driver to fetch the list from `containerengine`.

**Comment by jlamillan** [comment]
Fix is available in OKE cluster drivers v1.8.2+
